name: Build-Lean-lede
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master
  #   paths:
  #     -  'lean-lede/x86_64/.config'
  schedule:
        - cron: 0 */6 * * *

jobs:
   MT7621:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare environment.
      env:
          DEBIAN_FRONTEND: noninteractive
      run: |
        bash <(curl -fsSL https://raw.githubusercontent.com/dn0451/My-action/master/lean-lede/prenv.sh)
        
    - name: 检出
      uses: actions/checkout@v2
      with:
        repository: coolsnowwolf/lede
        
    - name: 加载客制化配置
      run: |
        curl -fsSL https://raw.githubusercontent.com/dn0451/My-action/master/lean-lede/mt7621/.config >.config
        bash <(curl -fsSL https://raw.githubusercontent.com/dn0451/My-action/master/lean-lede/diy.sh)
        make defconfig
        
    - name: 加载包
      run: |
        make download -j8
        find dl -size -1024c -exec rm -f {} \;
        
    - name: 当多核编译失败时将回滚到单核编译
      run: |
        echo -e "$(nproc) thread compile"
        sudo df -h
        make -j$(nproc) || make -j2 || make -j1 V=s
        sudo df -h
        
    - name: 打包Packages
      if: success()
      run: |
        cd bin
        zip -r -o -q -9  mt7621-Package.zip . -i *.ipk
        #curl -F "token=${{ secrets.UPLOAD_TOKEN }}" -F "location=Router/LEDE/XiaoMi/XiaoMi-AC2100/Lean-Package" -F "file=@mt7621-Package.zip" ${{ secrets.MAIN_UPLOAD_PROCESSOR }}
        #curl --socks5 ${{ secrets.PROXY_ADDR }} -U ${{ secrets.PROXY_USER }} -F "token=${{ secrets.UPLOAD_TOKEN }}" -F "location=Router/LEDE/XiaoMi/XiaoMi-AC2100/Lean-Package" -F "file=@mt7621-Package.zip" ${{ secrets.CN_STATION_PROCESSOR }}
        
    - name: 打包firmware (Without packages)
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: mt7621
        path: lede/bin/targets/*/*
